### ISSUE TITLE
package python3-dnf-plugin-post-transaction-actions is break

### ISSUE THREAD

**Issue by hgmiguel** [amazonlinux/smart-restart#5]
Hi, the smart-restart app depends on python3-dnf-plugin-post-transaction-actions that are currently broken.
 I tried configuring a simple post-script and got the following output.

This is a known issue on AL2023 https://github.com/amazonlinux/amazon-linux-2023/issues/732 

Can you please upgrade the `python3-dnf-plugin-post-transaction-actions` package? 

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf/plugin.py", line 104, in _caller
    getattr(plugin, method)()
  File "/usr/lib/python3.9/site-packages/dnf-plugins/post-transaction-actions.py", line 146, in transaction
    command = self._replace_vars(ts_item, a_command)
  File "/usr/lib/python3.9/site-packages/dnf-plugins/post-transaction-actions.py", line 104, in _replace_vars
    result = libdnf.conf.ConfigParser_substitute(command, vardict)
AttributeError: module 'libdnf.conf' has no attribute 'ConfigParser_substitute'
```

**Comment by ThatStasGuy** [comment]
Hi hgmiguel,

Thanks for raising this issue with us. `smart-restart` depends on the latest version of `python3-dnf-plugin-post-transaction-actions` which is an external dependency coming from the package repos. Unfortunately, we need to wait until `python3-dnf-plugin-post-transaction-actions` is fixed and made public.

Until then, I'll keep the issue open to keep track.

**Comment by ThatStasGuy** [comment]
We have updated the dependencies of smart-restart. Please update your system to the latest release:
```
sudo dnf upgrade --releasever=2023.6.20250107
```
(running `sudo dnf upgrade` w/o the `--releasever` flag will suggest the latest release if run at a later point in time)
This should pick up the latest version of `python3-dnf-plugin-post-transaction-actions` thus fixing the issue. The fixing release is `python3-dnf-plugin-post-transaction-actions-4.3.0-13.amzn2023.0.5`.

I'm going to close the issue, feel free to re-open or raise a new issue if you encounter issues with this package. Thanks again.
